apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    app: ft_services
    tier: influxdb
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: ft_services
    tier: influxdb
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ft_services
    tier: influxdb
  name: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: ft_services
    tier: influxdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: ft_services
    tier: influxdb
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: influxdb
  template:
    metadata:
      labels:
        app: ft_services
        tier: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:alpine
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        env:
        - name: INFLUXDB_DB
          value: influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim