apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft_services
    tier: nginx
spec:
  ports:
  - port: 443
    name: https
  - port: 80
    name: http
  - port: 22
    name: ssh
  selector:
    app: ft_services
    tier: nginx
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: ft_services
    tier: nginx
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
        - containerPort: 22
          name: ssh
