apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    app: ft_services
    tier: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ft_services
    tier: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
    tier: wordpress
spec:
  ports:
    - port: 80
      nodePort: 5050
  selector:
    app: ft_services
    tier: wordpress
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: ft_services
    tier: wordpress
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_TABLE_PREFIX
          value: wp_
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim