# docker stack rm ft_services
# docker stack deploy --compose-file docker-compose.yml ft_services

version: '3.7'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./srcs/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress
    ports:
      - 5050:80
    volumes:
      - ./srcs/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5000:80
    environment:
      PMA_HOST: mysql:3306

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./srcs/grafana/provisioning:/etc/grafana/provisioning
      - ./srcs/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  influxdb:
    image: influxdb:alpine
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: admin
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - ./srcs/influxdb:/var/lib/influxdb/

  telegraf:
    image: telegraf
    environment:
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: admin
      INFLUXDB_DB: telegraf
      INFLUXDB_URL: http://influxdb:8086
    volumes:
      - ./srcs/telegraf:/etc/telegraf/

  ftps:
    image: mikatux/ftps-server
    volumes:
      - ./srcs:/home/admin
    environment:
      USER: admin
      PASSWORD: admin
    ports:
      - "21:21"
      - "3001-3005:3001-3005"
    volumes:
      - ./srcs/ftps/ftps.crt:/etc/ssl/certs/ftps.crt
      - ./srcs/ftps/ftps.key:/etc/ssl/private/ftps.key

  nginx:
    image: iliyan/docker-nginx-sshd
    ports:
      - 80:80
      - 443:443
      - 23:22