apiVersion: 1

datasources:
- name: Analysis Server
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: telegraf
  isDefault: true
  version: 1
  editable: false
  basicAuth: false
  basicAuthUser: admin
  basicAuthPassword: admin
